version: '{build}'
skip_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '2.1.{version}.0'
  package_version: '2.1.{version}.0'
  assembly_version: '2.1.0.0'
  file_version: '2.1.{version}.0'
  informational_version: '2.1.{version}'
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Flatwhite.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 4nsYafkz2c0dh7jxX9Qgc6QI4EzJFpX3YwfGUaTc0pgYoqxWYwRxlUiDbXHOdBn7
  skip_symbols: true
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: FIa3nJSh965OYhhlpmzLv6H9Q2pvIMa8e0xgttC0A1gzoJCCRfBVF2+2L9BElFaJ
  artifact: /Flatwhite.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master